version: "3.9"

services:
  db: 
    image: postgres:13
    container_name: perspective_week1_postgres 
    environment: 
      POSTGRES_USER: perspective_user
      POSTGRES_PASSWORD: perspective_pass
      POSTGRES_DB: perspective_db
    ports:
      - "5432:5432"
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: