version: "3.9"

services:
  db:
    image: postgres:13
    container_name: perspective_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - perspective_net

  redis:
    image: redis:7-alpine
    container_name: perspective_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - perspective_net

  ingestion_service:
    build:
      context: ../backend
      dockerfile: ingestion_service/Dockerfile
    container_name: perspective_ingestion_service
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../.env
    networks:
      - perspective_net

  synthesis_service:
    build:
      context: ../backend
      dockerfile: synthesis_service/Dockerfile
    container_name: perspective_synthesis_service
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../.env
    networks:
      - perspective_net
    ports:
      - "8000:8000"

  processing_service:
    build:
      context: ../backend
      dockerfile: processing/Dockerfile
    container_name: perspective_processing_service
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../.env
    networks:
      - perspective_net

  api_service:
    build:
      context: ../backend
      dockerfile: api_service/Dockerfile
    container_name: perspective_api_service
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - perspective_net
    ports:
      - "8001:8001"


volumes:
  db_data:

networks:
  perspective_net: